(function(){'use strict';
const $=id=>document.getElementById(id), Core=window.OreCore;
const paths={pick:'M4 20 14 10M2 21l2 1 13-13-2-2ZM8 4l4-2 5 2 5 6-5-3-5-1-4 1Z',gem:'m12 2 8 6-3 11-5 3-5-3L4 8Zm0 0L9 10l3 12 4-12Zm-8 6 5 2 7 0 4-2',coin:'M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0ZM12 7v10m3-8h-4a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4H9',bolt:'m13 2-8 12h6l-1 8 9-13h-6Z',chart:'M3 3v18h18M6 15l4-5 4 3 7-8',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v5l3 2',trophy:'M7 3h10v7a5 5 0 0 1-10 0ZM7 5H3v3a4 4 0 0 0 4 4m10-7h4v3a4 4 0 0 1-4 4m-5 3v5m-4 1h8',bag:'M5 7h14l2 14H3ZM8 7V5a4 4 0 0 1 8 0v2',settings:'m10 3 4 0 1 3 3 1 3 1-1 4 1 3-3 2-3 1-1 3h-4l-1-3-3-1-3-2 1-3-1-4 3-1 3-1ZM16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',upgrade:'M5 20V9m7 11V4m7 16V11M2 9l3-3 3 3m1-5 3-3 3 3m1 7 3-3 3 3',fire:'M12 2c1 6-5 6-2 11 2-1 4-3 4-6 3 3 6 6 5 10a7 7 0 0 1-14 0C4 11 7 7 12 2ZM12 14c-3 3-3 5 0 7 3-2 3-4 0-7',gift:'M3 8h18v5H3Zm2 5v8h14v-8M12 8v13m0-13C4 9 3 2 8 3c2 0 4 5 4 5Zm0 0c8 1 9-6 4-5-2 0-4 5-4 5',play:'m9 5 10 7-10 7Z',info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 11v6m0-10v1',cloud:'M7 18H6a4 4 0 0 1-1-8 7 7 0 0 1 13-2 5 5 0 0 1 0 10h-1m-9-3 3 3 5-6',close:'m6 6 12 12M6 18 18 6',lock:'M6 10h12v11H6Zm2 0V6a4 4 0 0 1 8 0v4m-4 4v3',drill:'M6 3h12v5H6Zm1 5h10v6H7Zm2 6h6l-3 8Zm0-3h6M4 5H2m20 0h-2'};
function icon(name){return '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="'+(paths[name]||paths.gem)+'"/></svg>';}
function icons(scope=document){scope.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let state=Core.createState(),tab='tools',signature='',ready=false,saveStatus='localSave',modalKind='',boardKind='balance',busyAd=false,cloudChoicePending=false,lastFrame=performance.now(),lastRender=0;
const rewardSession=Core.createRewardSession();
const pauses=new Set(['loading']), audio=new OreAudio(),scene=new OreScene($('mine-scene'));
function tr(key,vars={}){let str=(OreText[state.settings.language]||OreText.ru)[key]??key;return str.replace(/\{(\w+)\}/g,(_,k)=>vars[k]??(k==='n'?'01':''));}
function num(value,digits=1){return new Intl.NumberFormat(state.settings.language==='ru'?'ru-RU':'en-US',{maximumFractionDigits:digits,notation:Math.abs(value)>=10000000?'compact':'standard'}).format(value);}
function text(id,value){const el=$(id);if(el&&el.textContent!==String(value))el.textContent=value;}
function translated(scope=document){scope.querySelectorAll('[data-t]').forEach(el=>el.textContent=tr(el.dataset.t));scope.querySelectorAll('[data-title]').forEach(el=>{el.title=tr(el.dataset.title);el.setAttribute('aria-label',tr(el.dataset.title));});}
const platform=new OrePlatform({onPause:pause,onResume:resume,onStatus:key=>{saveStatus=key;updateSave();}});
function updateSave(){text('save-status',tr(saveStatus));}
function pause(reason){pauses.add(reason);audio.pause(reason);platform?.gameplay(false);if(ready)save(false);}
function resume(reason){pauses.delete(reason);audio.resume(reason);lastFrame=performance.now();if(ready)platform.gameplay(pauses.size===0);}
function save(flush=false,cloud=true){if(!ready||cloudChoicePending)return Promise.resolve(false);state.updatedAt=Date.now();return platform.save(state,{flush,cloud});}
function changed(sound){state.updatedAt=Date.now();platform.writeLocal(state);if(sound)audio.sfx(sound);render(true);}
function toast(message,error=false){const el=document.createElement('div');el.className='toast'+(error?' error':'');el.textContent=message;$('toasts').append(el);setTimeout(()=>el.remove(),3800);while($('toasts').children.length>3)$('toasts').firstChild.remove();}
let wheelWinTimer=0;
function placeWheelWin(){const notice=$('wheel-win');const host=$('modal').open?$('modal'):document.body;if(notice.parentElement!==host)host.append(notice);}
function hideWheelWin(){clearTimeout(wheelWinTimer);$('wheel-win').hidden=true;}
function showWheelWin(message){hideWheelWin();placeWheelWin();text('wheel-win-message',message);$('wheel-win').hidden=false;wheelWinTimer=setTimeout(hideWheelWin,7000);}
function oreDef(id=state.selectedOre){return Core.ORES.find(o=>o.id===id);}
function build(){signature=state.settings.language+'|'+state.unlocked.join()+'|'+tab;document.documentElement.lang=state.settings.language;document.title=tr('gameName');document.body.classList.toggle('reduced-motion',state.settings.reducedMotion);translated();
 $('ore-tabs').innerHTML=Core.ORES.map(o=>'<div class="ore-tab" id="ore-badge-'+o.id+'" style="--ore:'+o.color+'"><span class="ore-dot"></span><span>'+tr(o.id)+'</span><b id="chance-badge-'+o.id+'"></b></div>').join('');
 $('chance-list').innerHTML=Core.ORES.slice(1).map(o=>'<div class="chance-row" id="chance-row-'+o.id+'"><span class="resource-gem" style="--ore:'+o.color+'"></span><div><strong>'+tr(o.id)+'</strong><span id="chance-effect-'+o.id+'"></span></div><button class="upgrade-buy" data-chance="'+o.id+'"><span id="chance-cost-'+o.id+'"></span></button><button class="chance-ad" data-ad-chance="'+o.id+'" title="'+tr('chanceAd')+'">▶ +1%<small>'+tr('adShort')+'</small></button></div>').join('');
 $('smelt-ore').innerHTML=Core.ORES.map(o=>'<option value="'+o.id+'">'+tr(o.id)+'</option>').join('');
 $('smelt-ore').value=state.smeltOre;
 $('sale-details').open=state.settings.inventoryExpanded;
 $('inventory').innerHTML=Core.ORES.filter(o=>state.unlocked.includes(o.id)).map(o=>[false,true].map(ref=>'<div class="inventory-row"><span class="resource-name"><span class="resource-gem '+(ref?'ingot':'')+'" style="--ore:'+o.color+'"></span><span>'+tr(o.id)+'<small>'+tr(ref?(o.id==='coal'?'coke':'refined'):'raw')+' · <span id="price-'+o.id+'-'+ref+'"></span> ◉</small></span></span><span class="inventory-count" id="count-'+o.id+'-'+ref+'">0</span><button class="sell-button" data-sell="'+o.id+'" data-refined="'+ref+'" title="'+tr('sellAll')+'">'+tr('sell')+' <span id="sell-'+o.id+'-'+ref+'"></span> ◉</button></div>').join('')).join('');
 const upgradeKeys=tab==='tools'?['click','auto']:['smeltSpeed','smeltCapacity'];const names={click:'pickName',auto:'autoName',smeltSpeed:'speedName',smeltCapacity:'capacityName'};const marks={click:'pick',auto:'drill',smeltSpeed:'fire',smeltCapacity:'upgrade'};
 $('upgrade-list').innerHTML=upgradeKeys.map(key=>'<div class="upgrade-card" data-key="'+key+'"><div class="upgrade-heading"><div class="upgrade-art">'+icon(marks[key])+'</div><div><h3>'+tr(names[key])+'</h3><div class="level" id="level-'+key+'"></div></div></div><div class="upgrade-effect" id="effect-'+key+'"></div><button class="upgrade-buy" data-buy="'+key+'"><span id="buy-label-'+key+'"></span><span class="price" id="cost-'+key+'"></span></button></div>').join('');
 document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('selected',b.dataset.tab===tab);b.setAttribute('aria-pressed',b.dataset.tab===tab);});updateSave();
}
function render(force=false){if(signature!==state.settings.language+'|'+state.unlocked.join()+'|'+tab)build();const st=Core.getStats(state),ore=oreDef();
 text('balance',num(state.balance,2)+' ◉');text('stock',num(Object.values(state.ores).reduce((n,o)=>n+o.raw+o.refined,0))+' '+tr('units'));text('click-yield',num(st.clickYield)+' '+tr('oreUnit'));text('production',num(st.orePerSecond)+' '+tr('oreSec'));text('income',num(st.potentialIncome,2));text('scene-ore',tr('vein',{ore:tr(ore.id),n:ore.multiplier}));text('depth-label','−'+120+' '+tr('meter'));
 const odds=Core.chances(state);
 text('click-milestone',tr('clickMilestone',{n:num(state.stats.clicks,0)}));
 Core.ORES.forEach(o=>{$('ore-badge-'+o.id).hidden=odds[o.id]===0;text('chance-badge-'+o.id,odds[o.id]+'%');if(o.id==='coal')return;const price=Core.chanceCost(state,o.id),available=Core.chanceAvailable(state,o.id),required=Core.unlockClicks(o.id);const reason=!available?tr('requiresHits',{n:num(required,0),left:num(Math.max(0,required-state.stats.clicks),0)}):state.chanceLevels[o.id]>=20?tr('maxLevel'):!Core.chanceDonor(state,o.id)?tr('chanceBudgetFull'):odds[o.id]+'% → '+(odds[o.id]+1)+'%';text('chance-effect-'+o.id,reason);text('chance-cost-'+o.id,!available?'🔒':Number.isFinite(price)?num(price)+' ◉':'—');const button=document.querySelector('[data-chance="'+o.id+'"]');button.disabled=state.balance<price||!Number.isFinite(price);button.setAttribute('aria-label',tr(o.id)+': '+reason);$('chance-row-'+o.id).classList.toggle('ore-locked',!available);const ad=document.querySelector('[data-ad-chance="'+o.id+'"]');ad.hidden=!available;ad.disabled=busyAd||!Core.canAdChance(state,o.id);ad.setAttribute('aria-label',tr('chanceAd')+': '+tr(o.id));});
 $('smelt-ore').value=state.smeltOre;$('smelt-ore').disabled=!!state.smelt;
 const multiplier=Core.incomeMultiplier(state);
 const rawValue=multiplier*Core.ORES.reduce((sum,o)=>sum+state.ores[o.id].raw*state.market.rate*o.multiplier,0);
 const allValue=rawValue+multiplier*Core.ORES.reduce((sum,o)=>sum+state.ores[o.id].refined*state.market.rate*o.multiplier*1.2,0);
 text('sell-everything-value',num(allValue,2)+' ◉');text('sell-raw-value',num(rawValue,2)+' ◉');
 $('sell-everything').disabled=allValue===0;$('sell-raw').disabled=rawValue===0;
 text('sell-refined-value',num(allValue-rawValue,2)+' ◉');$('sell-refined').disabled=allValue===rawValue;
 updateFortune();updateTimeRewards();
 text('sale-toggle-label',tr($('sale-details').open?'collapse':'expand'));
 text('action-furnace-note',tr('furnaceSelection',{ore:tr(state.smeltOre)}));
 const marketCountdown=Math.max(0,Math.ceil((state.market.nextAt-Date.now())/1000))+tr('secondShort');text('market-rate',state.market.rate);text('rock-market-rate',state.market.rate);text('market-timer',marketCountdown);text('rock-market-timer',marketCountdown);let diff=state.market.rate-state.market.previous;text('rate-change',diff===0?'—':tr(diff>0?'rateUp':'rateDown',{n:Math.abs(diff)}));$('rate-change').style.color=diff<0?'#ecac8b':'#85d3b3';
 const history=state.market.history.length>1?state.market.history:[state.market.rate,state.market.rate];let points=history.map((v,i)=>[i*240/(history.length-1),61-(v-1)/14*54]);let line=points.map(p=>p.join(',')).join(' ');$('market-chart').innerHTML='<defs><linearGradient id="chart-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#72cbab" stop-opacity=".23"/><stop offset="1" stop-color="#72cbab" stop-opacity="0"/></linearGradient></defs><path d="M0 61H240M0 33H240M0 7H240" stroke="#2d3c43" stroke-dasharray="3 5" fill="none"/><polygon points="0,66 '+line+' 240,66" fill="url(#chart-fill)"/><polyline points="'+line+'" fill="none" stroke="#77c3a4" stroke-width="2"/><circle cx="240" cy="'+points.at(-1)[1]+'" r="3" fill="#a3e0c5"/>';
 for(const o of Core.ORES){if(!state.unlocked.includes(o.id))continue;for(const ref of[false,true]){const count=state.ores[o.id][ref?'refined':'raw'],price=multiplier*state.market.rate*o.multiplier*(ref?1.2:1);text('price-'+o.id+'-'+ref,num(price,2));text('count-'+o.id+'-'+ref,num(count));text('sell-'+o.id+'-'+ref,num(count*price,2));const button=document.querySelector('[data-sell="'+o.id+'"][data-refined="'+ref+'"]');button.disabled=count===0;button.setAttribute('aria-label',tr('sellAll')+': '+tr(o.id)+' '+tr(ref?(o.id==='coal'?'coke':'refined'):'raw')+', '+num(count*price,2)+' ◉');}}
 const effects={click:tr('clickEffect',{a:st.clickYield,b:st.clickYield+Core.oreMultiplier(state)}),auto:tr('autoEffect',{a:num(st.autoRate),b:num(st.autoRate+.5)}),smeltSpeed:tr('speedEffect',{a:num(st.smeltDuration,2),b:num(Math.max(.5,8*Math.pow(.9,state.upgrades.smeltSpeed+1)),2)}),smeltCapacity:tr('capacityEffect',{a:st.smeltCapacity,b:st.smeltCapacity+1})};
 document.querySelectorAll('[data-buy]').forEach(b=>{const k=b.dataset.buy,cost=st.prices[k];text('level-'+k,tr('level',{n:state.upgrades[k]}));text('effect-'+k,Number.isFinite(cost)?effects[k]:tr('maxLevel'));text('buy-label-'+k,tr(state.upgrades[k]?'upgrade':'buy'));text('cost-'+k,Number.isFinite(cost)?num(cost)+' ◉':tr('maxLevel'));b.disabled=!Number.isFinite(cost)||state.balance<cost;});
 text('upgrade-count',tr('totalUpgrades',{n:Object.values(state.upgrades).reduce((a,b)=>a+b,0)}));const batch=state.smelt;
 text('smelt-title',batch?tr('smeltRunning',{ore:tr(batch.type)}):tr('readyFurnace'));text('smelt-detail',tr('smeltFormula',{n:batch?batch.amount:st.smeltCapacity}));text('smelt-duration',tr('smeltDuration',{n:num(batch?batch.duration:st.smeltDuration,2)}));text('smelt-time',batch?num(batch.elapsed,1)+' / '+num(batch.duration,1)+tr('secondShort'):'');$('smelt-progress').style.width=(batch?Math.min(100,batch.elapsed/batch.duration*100):0)+'%';$('furnace-art').classList.toggle('running',!!batch);$('auto-smelt').checked=state.autoSmelt;
 $('smelt-button').disabled=!!batch||!state.ores[state.smeltOre].raw;$('smelt-button').querySelector('span:last-child').textContent=tr(batch?'smeltBusy':'startSmelt');
 if(force)scene.draw(performance.now(),'coal',state.settings.reducedMotion,state.upgrades.auto,0,Core.chances(state));
}
function mine(){if(!ready||pauses.size)return;Core.mine(state);audio.sfx('mine');scene.hit(performance.now());changed();}
function openModal(kind,title,html){modalKind=kind;text('modal-title',tr(title));$('modal-content').innerHTML=html;$('modal').querySelector('.modal-top .close-modal').hidden=kind==='cloudChoice';translated($('modal'));icons($('modal'));if(!$('modal').open){pause('modal');$('modal').showModal();}placeWheelWin();}
function closeModal(){if($('modal').open&&!cloudChoicePending)$('modal').close();}
$('modal').addEventListener('cancel',e=>{if(cloudChoicePending)e.preventDefault();});
$('modal').addEventListener('close',()=>{modalKind='';placeWheelWin();resume('modal');});
function settings(){openModal('settings','settings','<div class="setting-row"><label for="language">'+tr('language')+'</label><select id="language"><option value="ru" '+(state.settings.language==='ru'?'selected':'')+'>Русский</option><option value="en" '+(state.settings.language==='en'?'selected':'')+'>English</option></select></div>'+['music','sound'].map(k=>'<label class="setting-row" for="setting-'+k+'"><span>'+tr(k)+'</span><input id="setting-'+k+'" class="toggle" type="checkbox" data-setting="'+k+'" '+(state.settings[k]?'checked':'')+'></label>').join('')+'<div class="modal-section"><p class="modal-status">'+tr('cloudInfo')+'</p>'+(platform.available&&!platform.authorized?'<button class="secondary" data-login>'+tr('login')+'</button>':'')+'<button class="secondary" id="help">'+tr('howToPlay')+'</button><p class="modal-status">'+tr('statsInfo',{ore:num(state.stats.totalMined),coins:num(state.stats.totalEarned,2)})+'</p></div>');}
function boardValue(kind){return kind==='balance'?state.balance:kind==='income'?Core.getStats(state).potentialIncome:kind==='clicks'?state.stats.clicks:state.stats.playSeconds;}
function boardScore(kind,value){return kind==='playtime'?Math.floor(value/3600)+tr('hourShort')+' '+Math.floor(value%3600/60)+tr('minuteShort'):num(value,kind==='clicks'?0:2)+(kind==='balance'?' ◉':kind==='income'?' ◉/'+tr('secondShort'):'');}
async function board(kind='balance'){boardKind=kind;const names={balance:'bestBalance',income:'bestIncome',clicks:'bestClicks',playtime:'bestPlaytime'};openModal('leaderboard','leaderboard','<div class="segmented leaderboard-tabs">'+Object.keys(names).map(k=>'<button data-board="'+k+'" class="'+(kind===k?'selected':'')+'">'+tr(names[k])+'</button>').join('')+'</div><div id="board-results" class="empty-state">'+tr(platform.available?'loading':'boardLocal')+'</div><div class="personal-score">'+tr('yourScore',{n:boardScore(kind,boardValue(kind))})+'</div>'+(platform.available&&!platform.authorized?'<button class="secondary" data-login>'+tr('login')+'</button>':''));if(!platform.available)return;try{const entries=await platform.leaderboard(kind);if(modalKind!=='leaderboard'||kind!==boardKind)return;$('board-results').className='';$('board-results').innerHTML=entries.length?'<ol class="board-list">'+entries.map(e=>'<li class="board-row"><span class="rank">'+esc(e.rank)+'</span><span class="player-name">'+esc(e.name||tr('anonymous'))+'</span><span class="score">'+boardScore(kind,e.score)+'</span></li>').join('')+'</ol>':'<div class="empty-state">'+tr('boardEmpty')+'</div>';}catch(_){if(modalKind==='leaderboard')text('board-results',tr('boardUnavailable'));}}
async function fulfill(purchase){if(!platform.cloud)return false;if(!Core.PRODUCTS.some(p=>p.id===purchase.productID)&&!['supporter_pack','ore_crate'].includes(purchase.productID))return false;Core.grantProduct(state,purchase.productID,purchase.purchaseToken);changed();return await save(true);}
function fullNum(n){return new Intl.NumberFormat(state.settings.language==='ru'?'ru-RU':'en-US',{maximumFractionDigits:0}).format(n);}
function productArt(p){const cell=p.spins?(p.spins===1?3:p.spins===3?4:5):p.permanent?2:p.multiplier===3?1:0;return '<div class="product-art" aria-hidden="true" style="--art-x:'+(cell%3*50)+'%;--art-y:'+Math.floor(cell/3)*100+'%"></div>';}
function productTitle(p){return p.spins?tr('spins'+p.spins):p.permanent?tr('oreForever'):tr('oreHours',{x:p.multiplier,n:p.seconds/3600});}
function adButtons(){return '<div class="shop-ads"><button class="primary" data-ad-reward="ore"></button><button class="primary" data-ad-reward="income"></button></div>';}
function updateAdButtons(){const a=Core.adStatus(state,Date.now()),amount=Core.adOreAmount(state);document.querySelectorAll('[data-ad-reward]').forEach(b=>{const raw=b.dataset.adReward==='ore',wait=raw?a.oreWait:a.boostWait;b.textContent=(raw?tr('oreAd',{n:fullNum(amount)}):tr('incomeAd'))+' · '+(wait?tr('waitAd',{time:timer(wait/1000)}):tr('adShort'));b.disabled=busyAd||wait>0||(raw&&!amount);if(raw&&!amount)b.title=tr('needAuto');});updateActiveBoosts();}
function updateActiveBoosts(){const rows=[];const add=(key,x,time,picture)=>rows.push('<div class="active-boost">'+icon(picture)+'<strong>'+tr(key,{x})+'</strong><span>'+time+'</span></div>');if(state.permanentOreX2)add('boostOre',2,tr('forever'),'gem');if(state.oreBoosts[0])add('boostOre',state.oreBoosts[0].multiplier,timer(state.oreBoosts[0].remaining),'pick');if(state.adIncomeRemaining>0)add('boostAdOre',2,timer(state.adIncomeRemaining),'play');if(state.boostRemaining>0)add('boostDrill',2,timer(state.boostRemaining),'drill');if(state.incomeBoosts[0])add('boostSales',state.incomeBoosts[0].multiplier,timer(state.incomeBoosts[0].remaining),'coin');const panel=$('active-boosts'),html=rows.join('');panel.hidden=!rows.length;if(panel.innerHTML!==html)panel.innerHTML=html;}
async function shop(){openModal('shop','shop',adButtons()+promoForm()+'<div class="shop-products">'+Core.PRODUCTS.map(p=>'<div class="product-card">'+productArt(p)+'<h3>'+esc(productTitle(p))+'</h3><button class="primary" data-product="'+p.id+'" disabled>'+tr(p.permanent&&state.permanentOreX2?'owned':'purchase',{price:p.price+' ₽'})+'</button></div>').join('')+'</div>'+(!platform.available?'<p class="modal-status">'+tr('localInfo')+'</p>':'<button class="secondary" id="restore">'+tr('restore')+'</button>'));updateAdButtons();if(!platform.available)return;const catalog=await platform.catalog();if(modalKind!=='shop')return;document.querySelectorAll('[data-product]').forEach(b=>{const p=Core.PRODUCTS.find(p=>p.id===b.dataset.product),item=catalog.find(i=>i.id===b.dataset.product),owned=p.permanent&&state.permanentOreX2;b.disabled=!item||!platform.cloud||owned;b.textContent=owned?tr('owned'):item?tr('purchase',{price:item.price}):tr('purchaseUnavailable');if(item?.getPriceCurrencyImage&&!owned){const img=document.createElement('img');img.className='price-currency';img.alt=item.priceCurrencyCode||'';img.src=item.getPriceCurrencyImage('small');b.append(img);}});}

async function login(){try{await save(true);const cloud=await platform.login();if(cloud){cloudChoicePending=true;const validated=Core.sanitizeState(cloud);openModal('cloudChoice','cloudChoice','<p class="modal-copy">'+tr('cloudChoiceDesc',{local:num(state.balance,2),cloud:num(validated.balance,2)})+'</p><div class="modal-actions"><button class="primary" id="use-cloud">'+tr('useCloud')+'</button><button class="secondary" id="use-local">'+tr('useLocal')+'</button></div>');$('use-cloud').onclick=async()=>{state=validated;cloudChoicePending=false;audio.configure(state.settings);signature='';changed();await save(true);closeModal();platform.restorePurchases(fulfill).catch(()=>{});};$('use-local').onclick=async()=>{cloudChoicePending=false;await save(true);closeModal();platform.restorePurchases(fulfill).catch(()=>{});};}else{await save(true);toast(tr('loggedIn'));settings();platform.restorePurchases(fulfill).catch(()=>{});}}catch(_){toast(tr('loginFailed'),true);}}
async function rewardedBonus(kind,id){if(busyAd||wheelSpinning||document.hidden)return;const limits=Core.adStatus(state,Date.now());if(kind==='wheel'&&!limits.wheelLeft||kind==='income'&&limits.boostWait||kind==='ore'&&(limits.oreWait||!Core.adOreAmount(state))||kind==='chance'&&!Core.canAdChance(state,id))return;if(!platform.available){toast(tr('adLocal'));return;}const oreAmount=Core.adOreAmount(state);busyAd=true;closeModal();render();await save(false);let granted=false;try{await platform.rewarded(()=>{granted=Core.grantAdReward(state,kind,Date.now(),id);if(granted){changed();save(true);}});}finally{busyAd=false;render();}if(!granted){toast(tr('adUnavailable'));return;}if(kind==='wheel'){wheel();spinWheel();}else toast(tr(kind==='chance'?'chanceUpgraded':kind==='ore'?'oreAdReward':'incomeReward',{ore:tr(id||'coal'),n:fullNum(oreAmount)}));}
let wheelSpinning=false;
function timer(seconds){seconds=Math.max(0,Math.ceil(seconds));return Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0');}
function prizePicture(p){const stroke='stroke="#513247" stroke-width="3" stroke-linejoin="round"';return '<svg class="prize-picture" viewBox="0 0 64 60" aria-hidden="true">'+(p.hits?'<path d="M12 51 39 17l8 7-27 34Z" fill="#b96732" '+stroke+'/><path d="m18 50 24-30" stroke="#ffcc77" stroke-width="4"/><path d="M9 16 28 4l17 5 14 21-18-10-13-5Z" fill="#a7edff" '+stroke+'/><path d="m14 15 15-7 14 5" fill="none" stroke="#fff8db" stroke-width="4"/>':p.hours?'<path d="M10 26Q8 8 24 9h19q13 1 12 17v22H10Z" fill="#bd7443" '+stroke+'/><path d="M10 25h45v23H10Z" fill="#e9a34d" '+stroke+'/><path d="M17 12v35m30-33v33" stroke="#ffe09b" stroke-width="5"/><rect x="27" y="25" width="12" height="14" rx="3" fill="#fff08f" '+stroke+'/><circle cx="16" cy="46" r="10" fill="#ffdc68" '+stroke+'/><path d="M16 41v10m-3-7h6" stroke="#c08735" stroke-width="3"/>'+(p.hours>=3?'<circle cx="44" cy="46" r="10" fill="#ffdf76" '+stroke+'/>':'')+(p.hours===10?'<path d="m32 2 5 6-5 7-5-7Z" fill="#a3fff4" '+stroke+'/>':''):'<path d="M38 7h12v6H38Z" fill="#e4e5ff" '+stroke+'/><circle cx="44" cy="32" r="19" fill="'+(p.multiplier===3?'#ce9bff':'#9ef2dd')+'" '+stroke+'/><circle cx="44" cy="32" r="13" fill="#fff4ce"/><path d="M44 22v11l7 4" fill="none" '+stroke+'/><path d="M24 3 5 33h14l-3 24 25-35H26l6-19Z" fill="'+(p.multiplier===3?'#ffab66':'#ffe472')+'" '+stroke+'/>')+'<path d="m5 8 2 4 4 2-4 2-2 4-2-4-3-2 3-2Z" fill="#fff5bc"/></svg>';}
function prizeLabel(p){return p.hits?tr('hitsPrize',{n:p.hits}):p.hours?tr('cashPrize',{n:p.hours}):tr('boostPrize',{x:p.multiplier,n:p.seconds/60});}
function updateFortune(){text('cash-basis',tr('cashBasis',{n:num(Core.prizeIncome(state),2)}));const next=timer((state.fortune.lastAt+Core.SPIN_PERIOD-Date.now())/1000);text('spin-status',tr('spinStatus',{n:num(state.fortune.spins),time:next}));text('wheel-status',tr('spinStatus',{n:num(state.fortune.spins),time:next}));const b=state.incomeBoosts[0],ad=Core.adStatus(state,Date.now()),multi=Core.incomeMultiplier(state),remaining=b&&b.multiplier===multi?Math.max(b.remaining,multi===2?state.adIncomeRemaining:0):state.adIncomeRemaining;text('income-buff',multi>1?tr('buffShort',{x:multi,time:timer(remaining)}):tr('fortuneTeaser'));if($('spin-wheel'))$('spin-wheel').disabled=wheelSpinning||busyAd||state.fortune.spins<1;if($('wheel-ad')){$('wheel-ad').disabled=wheelSpinning||busyAd||!ad.wheelLeft;text('wheel-ad',ad.wheelLeft?tr('wheelAd',{n:ad.wheelLeft}):tr('waitAd',{time:timer(ad.wheelWait/1000)}));}updateAdButtons();}
function timeRewards(){openModal('timeRewards','timeRewardsTitle','<p class="modal-copy">'+tr('timeRewardsHint')+'</p><div class="time-reward-grid">'+Core.TIME_REWARDS.map((r,i)=>'<button class="time-reward" data-time-reward="'+i+'"><span class="reward-gift">'+icon('gift')+'</span><strong>'+tr('rewardMinute',{n:r.at/60})+'</strong><b id="time-value-'+i+'"></b><small id="time-status-'+i+'"></small></button>').join('')+'</div>');updateTimeRewards();}
function updateTimeRewards(){const available=Core.TIME_REWARDS.map((r,i)=>({r,i})).filter(({r,i})=>rewardSession.elapsed>=r.at&&!rewardSession.claimed.includes(i));const next=Core.TIME_REWARDS.find(r=>r.at>rewardSession.elapsed);text('time-reward-summary',available.length?tr('timeReady',{n:available.length}):next?tr('timeNext',{time:timer(next.at-rewardSession.elapsed)}):tr('timeAllDone'));text('time-reward-count',rewardSession.claimed.length+' / 16');$('time-reward-progress').style.width=(rewardSession.elapsed/10800*100)+'%';if(modalKind!=='timeRewards')return;Core.TIME_REWARDS.forEach((r,i)=>{const claimed=rewardSession.claimed.includes(i),ready=rewardSession.elapsed>=r.at;const b=document.querySelector('[data-time-reward="'+i+'"]');b.disabled=claimed||!ready;b.classList.toggle('claimed',claimed);b.classList.toggle('available',ready&&!claimed);text('time-value-'+i,claimed?'✓':num(Core.timeRewardAmount(state,i),2)+' ◉');text('time-status-'+i,tr(claimed?'rewardClaimed':ready?'rewardClaim':'rewardWait'));});}
function promoForm(){return '<form id="promo-form" class="promo-form"><label for="promo-code">'+tr('promoTitle')+'</label><div><input id="promo-code" name="promo" maxlength="40" autocomplete="off" required placeholder="'+tr('promoPlaceholder')+'"><button class="secondary" type="submit">'+tr('activate')+'</button></div><p id="promo-result" role="status"></p></form>';}
function prizeAngle(index){return (index+.5)*360/Core.PRIZES.length;}
function wheel(){
 if(wheelSpinning)return;
 const colors=['#ffbd30','#ff8c32','#ffdb3e','#33cd9d','#26b6e8','#647ff5','#a06bf4','#ff9171','#ed5eaa','#bc5be2','#49bdee','#50d29d','#f6b94c'];
 const sectors=Core.PRIZES.map((p,i)=>colors[i%colors.length]+' '+i*360/Core.PRIZES.length+'deg '+(i+1)*360/Core.PRIZES.length+'deg').join(',');
 const labels=Core.PRIZES.map((p,i)=>'<span class="wheel-prize" style="--prize-angle:'+prizeAngle(i)+'deg" title="'+prizeLabel(p)+'">'+prizePicture(p)+(p.hits?'+'+p.hits:p.hours?p.hours+tr('hourShort'):'×'+p.multiplier+'<small>'+p.seconds/60+tr('minuteShort')+'</small>')+'</span>').join('');
 openModal('wheel','fortuneTitle','<p class="modal-copy">'+tr('wheelHelp')+'</p><div class="fortune-wheel-wrap"><div class="wheel-pointer">▼</div><div class="wheel-viewport"><div id="fortune-wheel" class="fortune-wheel"><div class="wheel-disc" style="background:conic-gradient('+sectors+')"></div>'+labels+'<img class="wheel-rim" src="assets/wheel-rim-v9.png" alt=""><b>◈</b></div></div></div><p id="wheel-status" class="wheel-status"></p><button id="spin-wheel" class="primary">'+tr('spinButton')+'</button><button id="wheel-ad" class="secondary reward-ad"></button><p class="ad-limit" data-t="wheelLimit"></p><p id="wheel-result" class="wheel-result">'+tr('wheelReady')+'</p><details class="prize-details"><summary>'+tr('prizeOdds')+'</summary>'+Core.PRIZES.map(p=>'<div><span class="prize-legend">'+prizePicture(p)+prizeLabel(p)+'</span><b>'+num(p.weight/100,1)+'%</b></div>').join('')+'<p id="cash-basis" class="modal-copy">'+tr('cashBasis',{n:num(Core.prizeIncome(state),2)})+'</p></details>');
 $('fortune-wheel').style.setProperty('--prize-step',(360/Core.PRIZES.length)+'deg');updateFortune();
}
function spinWheel(){if(wheelSpinning||modalKind!=='wheel'||document.hidden||busyAd)return;Core.tick(state,0,Date.now());const result=Core.spin(state,Date.now());if(!result)return;hideWheelWin();wheelSpinning=true;changed();save(true);const disc=$('fortune-wheel'),index=Core.PRIZES.findIndex(p=>p.id===result.id),prize=Core.PRIZES[index];disc.style.transition=state.settings.reducedMotion?'none':'transform 4s cubic-bezier(.12,.67,.15,1)';disc.style.transform='rotate('+(1800-(prizeAngle(index)))+'deg)';text('wheel-result',tr('spinning'));setTimeout(()=>{wheelSpinning=false;const message=prizeLabel(prize)+(prize.hours?' · +'+num(result.amount,2)+' ◉':'');if(modalKind==='wheel'){text('wheel-result',tr('won',{prize:message}));disc.style.transition='none';disc.style.transform='rotate('+(-(prizeAngle(index)))+'deg)';}showWheelWin(tr('won',{prize:message}));updateFortune();},state.settings.reducedMotion?50:4050);}
function eventHandlers(){
 document.addEventListener('submit',e=>{if(e.target.id!=='promo-form')return;e.preventDefault();const result=Core.redeemPromo(state,$('promo-code').value);text('promo-result',tr(result));if(result==='promoSuccess'||result==='promoUnlocked'){changed();save(true);$('promo-code').value='';}});
 document.addEventListener('click',e=>{if(e.target.closest('#spin-wheel'))spinWheel();});document.addEventListener('pointerdown',()=>{audio.unlock();if(document.hasFocus())resume('blur');},{passive:true});document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!$('modal').open&&!/INPUT|SELECT|TEXTAREA|BUTTON/.test(e.target.tagName)){e.preventDefault();audio.unlock();mine();}});
 $('mine-target').onclick=mine;$('mine-target').addEventListener('contextmenu',e=>e.preventDefault());
 document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
  if(b.dataset.open){({settings,leaderboard:board,shop,wheel,timeRewards}[b.dataset.open])();return;}
  if(b.classList.contains('close-modal')){closeModal();return;}
  if(b.dataset.tab){tab=b.dataset.tab;render(true);return;}
  if(b.hasAttribute('data-time-reward')){if(modalKind!=='timeRewards'||busyAd||document.hidden)return;Core.tick(state,0,Date.now());const amount=Core.claimTimeReward(state,rewardSession,Number(b.dataset.timeReward));if(amount!==null){changed();save(true);toast(tr('timeRewardPaid',{n:num(amount,2)}));}return;}
  if(b.dataset.adChance){rewardedBonus('chance',b.dataset.adChance);return;}
  if(b.id==='wheel-ad'){rewardedBonus('wheel');return;}
  if(b.dataset.adReward){rewardedBonus(b.dataset.adReward);return;}
  if(b.dataset.chance){if(pauses.size)return;if(Core.buyChance(state,b.dataset.chance)){changed('upgrade');toast(tr('chanceUpgraded',{ore:tr(b.dataset.chance)}));}return;}
  if(b.dataset.buy){if(pauses.size)return;if(Core.buyUpgrade(state,b.dataset.buy)){changed('upgrade');toast(tr('upgraded'));}return;}
  if(b.dataset.sell){if(pauses.size)return;Core.tick(state,0,Date.now());const amount=Core.sell(state,b.dataset.sell,b.dataset.refined==='true');if(amount){changed('sell');toast(tr('sold',{n:num(amount,2)}));platform.submitScores(state.balance,Core.getStats(state).potentialIncome,state.stats.clicks,state.stats.playSeconds);}return;}
  if(b.dataset.board){board(b.dataset.board);return;}
  if(b.hasAttribute('data-login')){b.disabled=true;await login();if(b.isConnected)b.disabled=false;return;}
  if(b.dataset.product){b.disabled=true;try{await platform.purchase(b.dataset.product,fulfill);toast(tr('purchaseSuccess'));}catch(_){toast(tr('purchaseFailed'),true);}if(modalKind==='shop')shop();return;}
  if(b.id==='restore'){b.disabled=true;try{await platform.restorePurchases(fulfill);toast(tr('restored'));}catch(_){toast(tr('purchaseFailed'),true);}b.disabled=false;return;}
  if(b.id==='help'){openModal('help','howToPlay','<p class="modal-copy">'+tr('help')+'</p><button class="primary close-modal">'+tr('returnGame')+'</button>');return;}
 });
 document.addEventListener('change',e=>{if(e.target.id==='language'){state.settings.language=e.target.value;signature='';changed();settings();}if(e.target.dataset.setting){state.settings[e.target.dataset.setting]=e.target.checked;audio.configure(state.settings);document.body.classList.toggle('reduced-motion',state.settings.reducedMotion);changed();}});
 const bulkSell=rawOnly=>{if(pauses.size)return;Core.tick(state,0,Date.now());const revenue=rawOnly==='refined'?Core.sellRefined(state):Core.sellAll(state,rawOnly);if(revenue){changed('sell');toast(tr('sold',{n:num(revenue,2)}));platform.submitScores(state.balance,Core.getStats(state).potentialIncome,state.stats.clicks,state.stats.playSeconds);}};
 $('sell-refined').onclick=()=>bulkSell('refined');$('sell-everything').onclick=()=>bulkSell(false);$('sell-raw').onclick=()=>bulkSell(true);
 $('sale-details').addEventListener('toggle',()=>{state.settings.inventoryExpanded=$('sale-details').open;changed();});
 $('smelt-ore').onchange=e=>{if(!state.smelt){state.smeltOre=e.target.value;changed();}};
 $('smelt-button').onclick=()=>{if(pauses.size)return;if(Core.startSmelt(state,state.smeltOre)){changed('smelt');}};$('auto-smelt').onchange=e=>{state.autoSmelt=e.target.checked;changed();};
 document.addEventListener('visibilitychange',()=>{if(document.hidden){pause('hidden');save(true);}else resume('hidden');});window.addEventListener('blur',()=>pause('blur'));window.addEventListener('focus',()=>resume('blur'));window.addEventListener('pagehide',()=>{pause('page');save(true);});window.addEventListener('pageshow',e=>{if(e.persisted){Object.assign(rewardSession,Core.createRewardSession());render(true);}resume('page');});
}
function frame(now){const dt=Math.min(.25,Math.max(0,(now-lastFrame)/1000));lastFrame=now;if(ready){const before=state.smelt;Core.tickRewardSession(rewardSession,pauses.size?0:dt);Core.tick(state,pauses.size?0:dt,Date.now());if(before&&before!==state.smelt&&!pauses.size)audio.sfx('smelt');if(!pauses.size)scene.draw(now,'coal',state.settings.reducedMotion,state.upgrades.auto,dt,Core.chances(state));if(now-lastRender>140){render();lastRender=now;}}requestAnimationFrame(frame);}
async function boot(){icons();const loaded=await platform.init();state=Core.sanitizeState(loaded.state||Core.createState());if(!loaded.state)state.settings.language=loaded.language;audio.configure(state.settings);Core.tick(state,0,Date.now());ready=true;eventHandlers();render(true);$('loading').remove();platform.ready();resume('loading');if(document.hidden)pause('hidden');save(false);setInterval(()=>save(false),5000);setInterval(()=>{if(!pauses.size)platform.submitScores(state.balance,Core.getStats(state).potentialIncome,state.stats.clicks,state.stats.playSeconds);},60000);requestAnimationFrame(frame);if(platform.cloud)platform.restorePurchases(fulfill).catch(()=>{});}
boot().catch(error=>{console.error('Orebound startup failed',error);const l=$('loading');if(l){l.innerHTML='<strong>Рудокоп</strong><span>Ошибка запуска / Startup error</span><button class="secondary" onclick="location.reload()">Обновить / Reload</button>';}});
})();
