(function(){'use strict';
class OreAudio{
  constructor(){this.ctx=null;this.settings={music:true,sound:true};this.reasons=new Set();this.timer=null;this.step=0;this.nodes=new Set();this.unlocked=false;this.generation=0;
    this.handlers={visibility:()=>document.hidden?this.pause('hidden'):this.resume('hidden'),blur:()=>this.pause('blur'),focus:()=>this.resume('blur'),hide:()=>this.pause('page'),show:()=>this.resume('page')};
    document.addEventListener('visibilitychange',this.handlers.visibility);window.addEventListener('blur',this.handlers.blur);window.addEventListener('focus',this.handlers.focus);window.addEventListener('pagehide',this.handlers.hide);window.addEventListener('pageshow',this.handlers.show);if(document.hidden)this.reasons.add('hidden');
  }
  async unlock(){try{if(!this.ctx){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=.32;this.master.connect(this.ctx.destination);}this.unlocked=true;await this.sync();}catch(_){}}
  configure(settings){this.settings={...this.settings,...settings};return this.sync();}
  pause(reason='manual'){this.reasons.add(reason);this.generation++;this.stop();if(this.master)this.master.gain.value=0;if(this.ctx&&this.ctx.state!=='closed')this.ctx.suspend().catch(()=>{});}
  resume(reason='manual'){this.reasons.delete(reason);return this.sync();}
  async sync(){const gen=++this.generation;try{if(!this.ctx||!this.unlocked)return;if(this.reasons.size||(!this.settings.music&&!this.settings.sound)){this.stop();this.master.gain.value=0;await this.ctx.suspend();return;}await this.ctx.resume();if(gen!==this.generation||this.reasons.size){if(this.reasons.size){this.master.gain.value=0;await this.ctx.suspend();}return;}this.master.gain.value=.32;if(this.settings.music&&!this.timer){this.musicStep();this.timer=setInterval(()=>this.musicStep(),480);}if(!this.settings.music&&this.timer){clearInterval(this.timer);this.timer=null;}}catch(_){}}
  stop(){clearInterval(this.timer);this.timer=null;for(const node of this.nodes){try{node.stop();}catch(_){}}this.nodes.clear();}
  tone(freq,vol,duration,type='sine',delay=0,endFreq){if(!this.ctx||this.reasons.size||this.ctx.state!=='running')return;const o=this.ctx.createOscillator(),g=this.ctx.createGain(),time=this.ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,time);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,time+duration);g.gain.setValueAtTime(.0001,time);g.gain.exponentialRampToValueAtTime(Math.max(.0002,vol),time+.015);g.gain.exponentialRampToValueAtTime(.0001,time+duration);o.connect(g);g.connect(this.master);this.nodes.add(o);o.onended=()=>{this.nodes.delete(o);o.disconnect();g.disconnect();};o.start(time);o.stop(time+duration+.04);}
  musicStep(){if(!this.settings.music||this.reasons.size)return;const notes=[220,0,329.63,0,293.66,0,261.63,0,196,0,293.66,0,261.63,0,329.63,0];let i=this.step++%notes.length;if(notes[i])this.tone(notes[i],.045,1.3,'sine');if(i%4===0)this.tone(i<8?110:98,.055,1.7,'sine');if(i===6||i===14)this.tone(659.25,.012,1.4,'triangle');}
  sfx(kind){if(!this.settings.sound||!this.ctx||this.reasons.size)return;switch(kind){case'mine':this.tone(640+Math.random()*200,.17,.055,'triangle',0,140);this.tone(160,.09,.13,'sine');break;case'sell':case'reward':this.tone(523,.13,.18,'sine');this.tone(784,.11,.32,'sine',.09);break;case'upgrade':this.tone(392,.1,.17,'triangle');this.tone(523,.1,.2,'triangle',.08);this.tone(784,.09,.3,'triangle',.16);break;case'smelt':this.tone(180,.07,.3,'triangle',0,80);break;default:this.tone(160,.04,.15,'sine');}}
  destroy(){this.stop();document.removeEventListener('visibilitychange',this.handlers.visibility);window.removeEventListener('blur',this.handlers.blur);window.removeEventListener('focus',this.handlers.focus);window.removeEventListener('pagehide',this.handlers.hide);window.removeEventListener('pageshow',this.handlers.show);this.ctx?.close().catch(()=>{});}
}
window.OreAudio=OreAudio;
})();
